addons:
    postgresql: 9.6

language: go
go:
  - "1.10"
  - "1.11"
  - tip

install:
  - go get -t -tags integration ./...

before_script: 
  - psql -c 'create database dotpgx_test;' -U postgres

script:
  - go test -tags integration
