addons:
    postgresql: 9.6

language: go
go:
  - "1.10"
  - "1.11"
  - tip

install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script: 
  - psql -c 'create database dotpgx_test;' -U postgres

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
